name: Feature Request
description: Suggest a new feature for LyraJS
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for LyraJS! 🎉

        **Note**: For component-specific features, consider filing in:
        - Core framework: [lyrajs-core](https://github.com/devway-eu/lyrajs-core/issues)
        - Project template: [lyrajs-template](https://github.com/devway-eu/lyrajs-template/issues)

  - type: dropdown
    id: component
    attributes:
      label: Which component would this feature affect?
      options:
        - Core Framework (@lyrajs/core)
        - Project Template (create-lyrajs)
        - Documentation
        - Website
        - Multiple components
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve?
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe the desired functionality...

        Example:
        ```typescript
        // Code example
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to contribute?
      options:
        - label: I'm willing to submit a pull request to implement this feature
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
